### ISSUE TITLE
How to remove style information?

### ISSUE THREAD

**Issue by Jamie-Cheung** [Josh00-Lu/CSBNet#1]
Hello, could you please provide the code of how to remove the style information of the style image (as shown in Figure 2 in the paper)?

**Comment by Josh00-Lu** [comment]
Thank you for the attention to our work. This pixel-level visualization demo can be easily implemented using Singular Value Decomposition (SVD). The process involves applying SVD to an image (with `C` channels), sorting the singular values, and then setting a threshold to sum the first K components (the bottom row of Figure 2). The remaining `C - K` components are summed separately (the top row of Figure 2). Since the `C - K` components tend to be quite dark, we applied a color inversion colormap for better visualization.
